config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # devise_for :users

  get "lectures", controller: 'talks', action: 'index', category: 'lecture'

  # resources :slides
  resources :events, :only => [:index, :show] do
    get "embed", :on => :member
  end
  resources :talks, :only => [:index, :show]
  get "play/:id" => 'slideshots#show', :as=>:play_slideshot
  get "eplay/:id" => 'slideshots#embed', :as=>:play_embedded_slideshot

  root "events#index"
end

app/models/talk.rb
class Talk < ApplicationRecord

  has_many :slides
  # belongs_to :user
  belongs_to :event
  belongs_to :location

  has_many   :plays

  mount_uploader :image, ImageUploader

  include VideoclipLocal
  include VideoclipYoutubeAlien
  include VideoclipLegacy

  scope :listable, -> { where(published: true, private: false) }
  scope :featured, -> { listable.where.not(featured_at: nil) }
  scope :last_published, ->(count=5) { listable.order(:published_at).reverse_order.limit(count) }
  scope :last_featured, ->(count=5) { featured.order(:featured_at).reverse_order.limit(count) }

  def self.find_by_sid(sid)
    if sid =~ /[^0-9]/
      talk=Talk.where("lower(nick) = ?", sid.downcase).first
      raise ActiveRecord::RecordNotFound, "Couldn't find Talk with sid='#{sid}'" if talk.nil?
      return talk
    else
      id=sid.to_i
      talk=Talk.find(id)
      return talk
    end
  end

  def to_jq_upload
    {
      "name" => read_attribute(:video),
      # "size" => video.size,
      # "url" => avatar.url,
      # "thumbnail_url" => avatar.thumb.url,
      # "delete_url" => picture_path(:id => id),
      # "delete_type" => "DELETE"
    }
  end


  # TODO: add validation on uniqueness of nick (donwcase)

  def listable?
    self.published && !self.private
  end

  def playable?
    video_playable? && (slides.count>0 || noslides?)
  end

  def publishable?
    !published && video_playable? && ( slides.count>0 && offset.present? || noslides? )
  end

  def featured?
    !self.featured_at.nil?
  end

  def featurable?
    self.listable?
  end

  def featured
    self.featured?
  end

  def featured!
    self.update_attribute(:featured_at, Time.now) if self.featurable?
  end

  def unfeatured!
    self.update_attribute(:featured_at, nil)
  end

  def featured=(v)
    if featured?
      self.update_attribute(:featured_at, nil) unless v
    else
      featured! if v
    end
  end

  def toggle_featured
    if self.featured?
      self.update_attribute(:featured_at, nil)
    else
      featured!
    end
  end

  def publish!
    if publishable?
      self.published = true
      self.published_at = Time.now
      if save
        if e=self.event
          e.last_published_at = self.published_at
          e.save
        else
          true
        end
      else
        false
      end
    else
      false
    end
  end

  def syncable?
    video_playable? && slides.count>0
  end

  def nick_or_id
    self.nick && !self.nick.empty? ? self.nick : self.id
  end

  def event_nick
    self.event.nil? ? "" : self.event.nick
  end

  # remove all the slides that happen before the first one (if any)
  def visible_slides
    ss=self.slides.untrashed.bytime
    while(ss.length>1 && ss[1].at==0)
      # puts "#{ss[0].at} - #{ss[1].at}"
      ss.shift
    end
    ss
  end

  def eventually_set_nick_for_private_video
    if self.private? && self.nick.blank?
      n="k"+SecureRandom.urlsafe_base64(8)
      while Talk.where(:nick => n).count > 0
        n="k"+SecureRandom.urlsafe_base64(8)
      end
      self.nick = n
    end
  end
  # -------------------------------------------------------- For synchronization
  def sync_slide_id
    @sync_slide ? @sync_slide.id : nil
  end

  def sync_slide_id=(i)
    @sync_slide = Slide.find(i)
  end

  def sync_time
    @sync_time
  end

  def sync_time=(t)
    @sync_time=t.to_i     # already in ms
  end

  def compute_offset
    unless @sync_time.nil? || @sync_slide.nil?
      puts "sync: offset prima = #{offset}"
      self.offset=sync_time - @sync_slide.show_at
      puts "sync: offset dopo  = #{offset}"
    end
  end

  # -------------------------------------------------------------- YouTube Video

  def youtube_title
    ml=60
    i=self.id.to_s
    e=self.event
    s=self.speaker
    t=self.title
    if e
      e = e.nick
      tb=i + " - " + e + " - " + s + ": "
      tt=tb + t
      if tt.length > ml
        if tb.length < ml - 3
          dl = ml - tb.length
          tt = tb + t.truncate(dl)
        else
          tb = i + " - " + e + " - "
          if tb.length < ml - 3
            dl = ml - tb.length
            tt = tb + s.truncate(dl)
          else
            tb = i + " - "
            dl = ml - tb.length
            tt = tb + t.truncate(dl)
          end
        end
      end
    else
      tb=i + " - " + s + ": "
      tt=tb + t
      if tt.length > ml
        if tb.length < ml - 3
          dl = ml - tb.length
          tt = tb + t.truncate(dl)
        else
          tb = i + " - "
          dl = ml - tb.length
          tt = tb + t.truncate(dl)
        end
      end
    end
    tt
  end

  def youtube_video_metadata
    {
      :title => youtube_title,
      :description => abstract,
      :category=>"Education",
      :private => false,
      :rate => "denied",
      :comment => "denied",
      :commentVote => "denied",
      :list => "denied",
      :embed => "allowed",
      :syndicate => "denied"
    }
  end

end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def index
    cat=params[:category]
    @lecture = params.key?(:category) && cat == "lecture"
    @talks = Talk.listable.where(lecture: @lecture).reverse_order.order(:published_at).paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @talk = Talk.find(params[:id])
    @embed = params[:embed]
    authorize! :read, @talk
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/helpers/talks_helper.rb
module TalksHelper
  # def render_markdown(t)
  #   BlueCloth.new(t).to_html.html_safe
  # end

  def large_image_for_talk(talk)
    if talk.image.present?
      image_tag talk.image.large.url, class: "img-responsive"
    elsif s=talk.slides.bytime.first
      image_tag s.image.large.url
    elsif talk.event && talk.event.image.present?
      image_tag talk.event.image.large.url, class: "img-responsive"
    else
      image_tag "large_placeholder.png", class: "img-responsive"
    end
  end
  def med_image_for_talk(talk)
    if talk.image.present?
      image_tag talk.image.med.url, class: "img-responsive"
    elsif s=talk.slides.bytime.first
      image_tag s.image.med.url
    elsif talk.event && talk.event.image.present?
      image_tag talk.event.image.med.url, class: "img-responsive"
    else
      image_tag "med_placeholder.png", class: "img-responsive"
    end
  end

  def video_path(t,ext="mp4")
    if t.video.present?
      if t.video_status != "ready"
        asset_path("processing.#{ext}")
      else
        t.video(ext)
      end
    else
      asset_path("default.#{ext}")
    end
  end
  def video_status_label(t)
    l = case t
        when "ready"
          "success"
        when "stored", "storing", "processing"
          "warning"
        when "missing", "absent", "error"
          "danger"
        end
    "<span class='label label-#{l}'>#{h t}</span>".html_safe
  end


  # TODO
  def video_url(t,ext="mp4")
    # "http://192.168.70.38:3000/uploads/talks/videos/000/000/290/0619061dad54675be1906f0b0c5c6a65722f149d.ogg?1439558240".html_safe
    "#{root_url}/#{video_path(t,ext)}".gsub("%2F", "/").gsub("%3F", "?").html_safe
  end
end

app/views/talks/_details.html.haml
#talk{class: "d-flex flex-row p-2 gap-3"}
  .immagine= large_image_for_talk(@talk)
  .media-body
    %h2.media-heading
      =@talk.title
      %br
      %small=@talk.subtitle
    %h4=@talk.speaker
    %p
      Recorded
      = @talk.date.strftime("%d %B %Y")
      in #{@talk.location.locality}, #{@talk.location.region}, #{@talk.location.country}
    - if @talk.event and @embed.nil?
      %p
        - if @talk.lecture
          %b Course:
          = link_to @talk.event.title, @talk.event
        -else
          %b Event:
          = link_to @talk.event.nickname, @talk.event
          - if @talk.event.title.present?
            \- #{@talk.event.title}

    - if @talk.abstract.present?
      %h4 Abstract
      .abstract
        = render_markdown @talk.abstract
    %p.pull-right Watched #{@talk.plays_count || 0} times.
    - if @embed
      =button_to_play_for_embed(@talk)
    - else
      =button_to_play(@talk)

app/views/talks/_talk.html.haml
%li{class: "talk card p-1"}
  .row
    %div{class: "col-md-9 d-flex flex-row p-2"}
      %div{class: "immagine d-flex align-items-center justify-content-center"}
        %a{href:'#'}= med_image_for_talk(talk)
      .media-body
        %h4=talk.speaker
        %h5.media-heading=talk.title
        %h6=talk.subtitle
        %div{class: "btn-group btn-group-sm", role: "group"}
          = link_to play_with_icon, play_slideshot_path(talk.nick_or_id), class: "btn btn-outline-primary"
          = link_to show_with_icon, talk_path(talk), class: "btn btn-outline-primary"
          - unless talk.event.nil? or noevent||=false
            =link_to index_with_icon("Event Page"), event_path(talk.event), class: "btn btn-outline-primary"
    .col-md-3
      - unless talk.event.nil? or noevent||=false
        %p
          =link_to talk.event.nickname, talk.event
      =time_tag talk.date
      -#
        %br
        =talk.location.locality
        \-
        =talk.location.country
      %br
      Watched #{talk.plays_count||0} times.

app/views/talks/index.html.haml
= content_title(@lecture ? "Lectures" : "Seminars")

= will_paginate @talks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

%ul{class: "talk_listing list-unstyled d-grid gap-3"}
  =render partial: "talk", collection: @talks

= will_paginate @talks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/talks/show.html.haml
= content_for :title do
  #{@talk.speaker} / "#{tronca(@talk.title, 32)}" - Details.

= render partial: 'talks/details'