config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # devise_for :users

  get "lectures", controller: 'talks', action: 'index', category: 'lecture'

  # resources :slides
  resources :events, :only => [:index, :show] do
    get "embed", :on => :member
  end
  resources :talks, :only => [:index, :show]
  get "play/:id" => 'slideshots#show', :as=>:play_slideshot
  get "eplay/:id" => 'slideshots#embed', :as=>:play_embedded_slideshot

  root "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :talks

  validates_presence_of :user_id, :on => :create, :message => "can't be blank"
  validates_presence_of :nick, :on => :create, :message => "can't be blank"
  validates_length_of   :nick, :within => 1..16, :on => :create, :message => "Should be at most 16 characters long"
  validates_presence_of :title, :on => :create, :message => "can't be blank"

  mount_uploader :image, ImageUploader

  def nickname
    nick
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, except: [:index]

  def index
    @events = Event.order(:last_published_at).reverse_order.paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def embed
    @user = @event.user
    if @user.can_embed_from?(request.referer)
      session[:embed] = true
      render :layout => 'embed'
    else
      render :template => "errors/error_noembed.html", :layout => false, :status => :forbidden
    end
    response.headers.except! 'X-Frame-Options'
  end

 private

  def set_event
    sid=params[:id]
    id=sid.to_i
    @event = id==0 ? Event.where("lower(nick) = ?", sid.downcase).last : Event.find(id)
    @talks = @event.talks.listable.order(:id).order(:date)
  end

end

app/helpers/events_helper.rb
module EventsHelper

  def large_image_for_event(event)
    if event.image.present?
      image_tag event.image.large.url, class: "img-responsive"
    else
      image_tag "large_placeholder.png", class: "img-responsive"
    end
  end
  def med_image_for_event(event)
    if event.image.present?
      image_tag event.image.med.url, class: "img-responsive"
    else
      image_tag "med_placeholder.png", class: "img-responsive"
    end
  end

end

app/views/events/_event.html.haml
%li{class: "talk card p-1"}
  .row
    %div{class: "col-md-6 d-flex flex-row p-2"}
      %div{class: "immagine piccola d-flex align-items-center justify-content-center"}
        %a{href: event_path(event), class:"float-start"}
          = med_image_for_event(event)
      .media-body
        %h4=link_to event.nick, event_path(event), class: "text-reset"
        %p=event.title || "-"
        -#.btn-group.btn-group
          =link_to show_with_icon("Details"), event_path(event), class: 'btn btn-default btn-xs'
        %p
          = event.talks.count
          = event.course? ? "lectures" : "talks"
    .col-md-6
      - if event.description.present?
        .well.short_description
          =render_markdown(truncate(event.description, length: 300))

app/views/events/embed.haml
= content_for :title do
  #{@event.nick} - event details

%ul.talk_listing.list-unstyled
  - @talks.each do |talk|
    %li.talk
      .well
        .row
          .col-md-9
            .media
              %a{href:'#', class:"float-start"}
                .immagine
                  = med_image_for_talk(talk)
              .media-body
                %h4=talk.speaker
                %h5.media-heading=talk.title
                %h6=talk.subtitle
                .btn-group.btn-group
                  = button_to_play_for_embed(talk, t="Watch")
                  -#= button_to_play(talk, t="Watch")
                  -# = link_to play_with_icon("watch"), play_slideshot_url(talk.nick_or_id),  target: "_parent", class: "btn btn-default btn-xs"
                  = link_to show_with_icon, talk_path(talk, :embed=>true), remote: true, class: 'btn btn-default btn-xs toajaxmodal', role: "button"
          .col-md-3
            =time_tag talk.date
            -#
              %br
              =talk.location.locality
              \-
              =talk.location.country
            %br
            Watched #{talk.plays_count||0} times.

app/views/events/index.html.haml
= content_title "Events"

= will_paginate @talks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer


%ul{class: "talk_listing list-unstyled d-grid gap-3"}
  =render partial: "event", collection: @events

= will_paginate @talks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/events/show.html.haml
= content_for :title do
  #{@event.nick} - event details


%div{class: "d-flex flex-row p-2 gap-3", id: "event"}
  .immagine
    =image_tag @event.image.large.url, class:"media-object img-rounded", width: "240"
  .media-body
    %h2.media-heading
      = @event.nick
      %br
      %small=@event.title
    %h4=@event.subtitle
    - if @event.description.present?
      .well=render_markdown @event.description

%h3= @event.course ? "Lectures" : "Seminars"
%ul{class: "talk_listing list-unstyled d-grid gap-3"}
  =render partial: "talks/talk", collection: @talks, locals: {:noevent => true}