config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # devise_for :users

  get "lectures", controller: 'talks', action: 'index', category: 'lecture'

  # resources :slides
  resources :events, :only => [:index, :show] do
    get "embed", :on => :member
  end
  resources :talks, :only => [:index, :show]
  get "play/:id" => 'slideshots#show', :as=>:play_slideshot
  get "eplay/:id" => 'slideshots#embed', :as=>:play_embedded_slideshot

  root "events#index"
end

app/views/layouts/_ajaxmodal.html.haml
#ajaxmodal{class: "modal fade container", tabindex: "-1", data: {keyboard: true}}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3.modal-title Loading
  .modal-body
    .modal-body-content
    .ajax-loader
  .modal-footer
    %button.btn{"data-dismiss" => "modal", :type => "button"} Close

app/views/layouts/_footer.html.haml
%footer{class: "bg-dark text-center text-white"}
  .container
    .content
      %p
        =image_tag "logo64.png", height: 64
        =link_to 'Slideshot', root_path
        \&copy; 2010-#{Time.now.year}
        =link_to "Giovanni Cangiani", 'mailto:giovanni.cangiani@epfl.ch'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav.html.haml
%header{class: "navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow"}
  =link_to "Slideshot", root_path, class: "navbar-brand col-md-3 col-lg-2 me-0 px-3"
  .navbar-nav
    %ul.nav.nav-pills
      %li.nav-item=link_to "Events", events_path, class: "nav-link px-3"
      %li.nav-item=link_to "Seminars", talks_path, class: "nav-link px-3"
      %li.nav-item=link_to "Lectures", lectures_path, class: "nav-link px-3"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minislideshot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? Rails.configuration.app[:site][:name_viewer] + ": " + yield(:title) : "#{Rails.configuration.app[:site][:name_viewer]}: #{controller_name} - #{action_name}"
    %meta{:content => content_for?(:description) ? yield(:description) : "#{Rails.configuration.app[:site][:name_viewer]}: #{controller_name} - #{action_name}", :name => "description"}
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true

    = yield(:head)
    = csrf_meta_tags
    -# moved to rack middleware in config/environments/production.rb
      - if Rails.env.production?
        :javascript
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', '#{Rails.configuration.app[:ga][:key]}']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
  %body{:class => "#{controller_name} #{action_name}"}
    =render 'layouts/nav'
    %main.container
      - if content_for?(:motto)
        %header.container
          .content
            = yield(:motto)
      - if content_for(:featured)
        #featured.hidden-xs
          .container
            = yield(:featured)
      #main.container{:role => "main"}
        .content
          = render 'layouts/messages'
          = yield
      #push
    =render 'layouts/footer'
    -#=render 'layouts/ajaxmodal'